config/routes.rb
Rails.application.routes.draw do
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/signout', to: 'sessions#destroy', name: :signout

  resources :advices, only: [:new, :create]
  resources :worries, only: [:index, :show, :new, :create]
  resources :my_worries, path: '/my/worries', only: [:index]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'message#show'
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
end

app/models/advice.rb
class Advice < ApplicationRecord
  belongs_to :user
  belongs_to :worry, counter_cache: :advices_count
  belongs_to :in_reply_to, class_name: self, optional: true, counter_cache: :replies_count
  has_many :replies, class_name: self, foreign_key: :in_reply_to_id

  scope :has_no_replies, -> { where(replies_count: 0) }
  scope :open, -> { where(closed_at: nil) }

  after_save :call_worry_after_save

  validates :detail, presence: true, length: { in: 1..35 }

  def self.not_mine(user_id)
    user_id ? where.not(user_id: user_id) : all
  end

  private

  def call_worry_after_save
    worry.send(:close_if_has_many_advices)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message
  def initialize(item)
    @item = item
  end

  def detail
    @item ? @item.detail : I18n.t('what_is_worring_you')
  end

  def reply
    case @item
    when Worry
      @item.advices.build
    when Advice
      @item.replies.build(worry: @item.worry)
    else
      Worry.new
    end
  end
end

app/models/reply.rb
class Reply
  attr_reader :message

  def initialize(item)
    @item = item
    @message = build_message
  end

  private

  def build_message
    case @item
    when Worry
      Message.new(nil)
    when Advice
      Message.new(@item.in_reply_to ? @item.in_reply_to : @item.worry)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :rememberable, :trackable

  has_many :accounts
end

app/models/worry.rb
class Worry < ApplicationRecord
  belongs_to :user

  has_many :advices

  scope :has_no_advices, -> { where(advices_count: 0) }
  scope :open, -> { where(closed_at: nil) }
  scope :closed, -> { where.not(closed_at: nil) }

  after_save :close_if_has_many_advices

  validates :detail, presence: true, length: { in: 1..35 }

  def self.mine(user_id)
    user_id ? where(user_id: user_id) : none
  end

  def self.not_mine(user_id)
    user_id ? where.not(user_id: user_id) : all
  end

  private

  def close_if_has_many_advices
    if advices_count >= 30
      self.update_column(:closed_at, Time.current)
      advices.all.update_all(closed_at: Time.current)
    end
  end
end

app/controllers/advices_controller.rb
class AdvicesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  # GET /advices/new
  def new
    @advice = Advice.new(advice_params)
    @reply = Reply.new(@advice)
  end

  # POST /advices
  # POST /advices.json
  def create
    @advice = Advice.new(advice_params)
    @advice.user = signed_in_user
    @reply = Reply.new(@advice)

    respond_to do |format|
      if @advice.save
        format.html { redirect_to root_path, notice: 'Advice was successfully created.' }
        format.json { render :show, status: :created, location: @advice }
      else
        format.html { render :new }
        format.json { render json: @advice.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def advice_params
      params.require(:advice).permit(:detail, :worry_id, :in_reply_to_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper

  protect_from_forgery with: :exception

  devise_group :user, contains: [:user]
end

app/controllers/message_controller.rb
class MessageController < ApplicationController
  def show
    items = [nil, nil]

    if Worry.open.count >= 3
      items += Worry.open.has_no_advices.not_mine(signed_in_user.try(:id)).order('RANDOM()').limit(3).to_a
      items += Advice.open.has_no_replies.not_mine(signed_in_user.try(:id)).order('RANDOM()').limit(5).to_a
    end

    @message = Message.new(items.shuffle.first)
  end
end

app/controllers/my_worries_controller.rb
class MyWorriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_my_worry, only: [:show, :edit, :update, :destroy]

  # GET /my_worries
  # GET /my_worries.json
  def index
    @my_worries = Worry.mine(signed_in_user.id).all
  end

  # GET /my_worries/1
  # GET /my_worries/1.json
  def show
  end

  # GET /my_worries/new
  def new
    @my_worry = MyWorry.new
  end

  # GET /my_worries/1/edit
  def edit
  end

  # POST /my_worries
  # POST /my_worries.json
  def create
    @my_worry = MyWorry.new(my_worry_params)

    respond_to do |format|
      if @my_worry.save
        format.html { redirect_to @my_worry, notice: 'My worry was successfully created.' }
        format.json { render :show, status: :created, location: @my_worry }
      else
        format.html { render :new }
        format.json { render json: @my_worry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /my_worries/1
  # PATCH/PUT /my_worries/1.json
  def update
    respond_to do |format|
      if @my_worry.update(my_worry_params)
        format.html { redirect_to @my_worry, notice: 'My worry was successfully updated.' }
        format.json { render :show, status: :ok, location: @my_worry }
      else
        format.html { render :edit }
        format.json { render json: @my_worry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /my_worries/1
  # DELETE /my_worries/1.json
  def destroy
    @my_worry.destroy
    respond_to do |format|
      format.html { redirect_to my_worries_url, notice: 'My worry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_my_worry
      @my_worry = MyWorry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def my_worry_params
      params.require(:my_worry).permit(:index)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    account = AccountService.authenticate(env['omniauth.auth'])
    sign_in(:user, account.user)
    redirect_to root_path
  end

  def destroy
    sign_out(:user)
    redirect_to root_path
  end
end

app/controllers/worries_controller.rb
class WorriesController < ApplicationController
  include WorriesHelper

  before_action :authenticate_user!, only: [:new, :create]
  before_action :set_worry, only: [:show]

  # GET /worries
  # GET /worries.json
  def index
    @worries = Worry.closed.all
  end

  # GET /worries/1
  # GET /worries/1.json
  def show
  end

  # GET /worries/new
  def new
    @worry = Worry.new
    @reply = Reply.new(@worry)
  end

  # POST /worries
  # POST /worries.json
  def create
    @worry = Worry.new(worry_params)
    @worry.user = signed_in_user
    @reply = Reply.new(@worry)

    respond_to do |format|
      if @worry.save
        format.html { redirect_to root_path, notice: 'Worry was successfully created.' }
        format.json { render :show, status: :created, location: @worry }
      else
        format.html { render :new }
        format.json { render json: @worry.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_worry
      @worry = Worry.includes(:advices).find(params[:id])
      @sorted_advices = sort_advices(@worry)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def worry_params
      params.require(:worry).permit(:detail)
    end
end

app/helpers/advices_helper.rb
module AdvicesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def signed_in_user
    @signed_in_user ||= user_signed_in? ? User.find(current_user['id']) : nil
  end
end

app/helpers/message_helper.rb
module MessageHelper
end

app/helpers/my_worries_helper.rb
module MyWorriesHelper
end

app/helpers/worries_helper.rb
module WorriesHelper
  def sort_advices(worry)
    worry.advices.to_a.each_with_object({}) do |advice, h|
      h[advice.in_reply_to_id] ||= []
      h[advice.in_reply_to_id] << advice
    end
  end
end

app/views/advices/_advice.html.erb
<%= form_for(advice) do |f| %>
  <% if advice.errors.any? %>
  <div class="card red lighten-4">
    <div class="card-content red-text text-darken-4">
      <ul>
        <% advice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  </div>
  <% end %>

  <div class="row">
    <div class="input-field col m6 offset-m3">
      <i class="material-icons prefix">mode_edit</i>
      <%= f.label :detail %>
      <%= f.text_area :detail, class: 'materialize-textarea', length: 35 %>
    </div>
  </div>


  <div class="row">
    <div class="center">
      <%= f.hidden_field :worry_id %>
      <%= f.hidden_field :in_reply_to_id %>
      <button class="btn waves-effect waves-light" type="submit" name="action"><%=t 'Post' %></button>
    </div>
  </div>
<% end %>

app/views/advices/_form.html.erb
<%= form_for(advice) do |f| %>
  <% if advice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(advice.errors.count, "error") %> prohibited this advice from being saved:</h2>

      <ul>
      <% advice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :detail %>
    <%= f.text_area :detail %>
  </div>

  <div class="field">
    <%= f.label :worry_id %>
    <%= f.text_field :worry_id %>
  </div>

  <div class="field">
    <%= f.label :in_reply_to_id %>
    <%= f.text_field :in_reply_to_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/advices/new.html.erb
<p class="flow-text blue-grey-text text-darken-4"><%= @reply.message.detail %></p>

<%= render @advice %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InReplyTo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>
    <nav class="blue-grey" role="navigation">
      <div class="nav-wrapper container"><%= link_to 'in-reply-to', root_path, id: 'logo-container', class: 'brand-logo' %>
        <ul class="right hide-on-med-and-down">
          <li><%= link_to t('Past Worries'), worries_path %></li>
          <% if signed_in?(:user) %>
          <li class="blue-grey darken-1"><%= link_to t('sign_out'), signout_path %></li>
          <% else %>
          <li class="blue-grey darken-1"><%= link_to t('sign_in'), '/auth/twitter' %></li>
          <% end %>
        </ul>

        <ul id="nav-mobile" class="side-nav">
          <li><%= link_to t('Past Worries'), worries_path %></li>
          <% if user_signed_in? %>
          <li class="blue-grey darken-1"><%= link_to t('sign_out'), signout_path %></li>
          <% else %>
          <li class="blue-grey darken-1"><%= link_to t('sign_in'), '/auth/twitter' %></li>
          <% end %>
        </ul>
        <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
      </div>
    </nav>

    <div class="section no-pad-bot" id="index-banner">
      <div class="container">
        <div class="row center">
          <%= notice %>
        </div>
      </div>

      <div class="container">
        <div class="card-panel">
          <%= yield %>
        </div>
      </div>
    </div>

    <footer class="page-footer transparent">
      <div class="container">
        <div class="row center">
          <ul>
            <li><%= link_to t('About in-reply-to'), 'https://github.com/kano-e/in-reply-to/blob/master/README.md', class: 'blue-grey-text text-darken-2' %></li>
          </ul>
        </div>
      </div>
    </footer>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/message/show.html.erb
<p class="flow-text blue-grey-text text-darken-4"><%= @message.detail %></p>

<% if user_signed_in? %>
<%= render @message.reply %>
<% else %>

<div class="row">
  <div class="input-field col m6 offset-m3">
    <i class="material-icons prefix">mode_edit</i>
    <%= text_area_tag :detail, '返信するにはログインが必要です。', class: 'materialize-textarea', disabled: true %>
  </div>
</div>

<div class="row">
  <div class="center">
    <%= link_to '/auth/twitter' do %>
      <button class="btn waves-effect waves-light blue-grey darken-1" type="submit" name="action"><%=t 'sign_in' %></button>
    <% end %>
  </div>
</div>
<% end %>

app/views/my_worries/_form.html.erb
<%= form_for(my_worry) do |f| %>
  <% if my_worry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(my_worry.errors.count, "error") %> prohibited this my_worry from being saved:</h2>

      <ul>
      <% my_worry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :index %>
    <%= f.text_field :index %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/my_worries/edit.html.erb
<h1>Editing My Worry</h1>

<%= render 'form', my_worry: @my_worry %>

<%= link_to 'Show', @my_worry %> |
<%= link_to 'Back', my_worries_path %>

app/views/my_worries/index.html.erb
<p class="blue-grey-text text-darken-4"><%=t('Your Worries') %></p>

<% if @my_worries.blank? %>
<div>
  <span class="red-text text-lighten-2"><%=t 'Not found.' %></span>
</div>
<% end %>

<% if @my_worries.present? %>
<table>
  <thead>
    <tr>
      <th><%=t 'worries' %></th>
      <th><%=t 'advices' %></th>
    </tr>
  </thead>

  <tbody>
    <% @my_worries.each do |worry| %>
      <tr>
        <td>
          <% if worry.closed_at? %>
          <%= link_to worry.detai, worry %>
          <% else %>
          <%= worry.detail %>
          <% end %>
        </td>
        <td><%=t worry.advices_count %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/my_worries/new.html.erb
<h1>New My Worry</h1>

<%= render 'form', my_worry: @my_worry %>

<%= link_to 'Back', my_worries_path %>

app/views/my_worries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Index:</strong>
  <%= @my_worry.index %>
</p>

<%= link_to 'Edit', edit_my_worry_path(@my_worry) %> |
<%= link_to 'Back', my_worries_path %>

app/views/worries/_advice.html.erb
<li class="collection-item">
<span><%= advice.detail %></span>
<% if @sorted_advices[advice.id].present? %>
<ul>
<% @sorted_advices[advice.id].each do |reply| %>
<%= render 'advice', advice: reply %>
<% end %>
</ul>
<% end %>
</li>

app/views/worries/_form.html.erb
<%= form_for(worry) do |f| %>
  <% if worry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(worry.errors.count, "error") %> prohibited this worry from being saved:</h2>

      <ul>
      <% worry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_area :detail %>
  </div>

  <div class="actions">
    <%= f.submit 'Post' %>
  </div>
<% end %>

app/views/worries/_worry.html.erb
<%= form_for(worry) do |f| %>
  <% if worry.errors.any? %>
  <div class="card red lighten-4">
    <div class="card-content red-text text-darken-4">
      <ul>
        <% worry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  </div>
  <% end %>

  <div class="row">
    <div class="input-field col m6 offset-m3">
      <i class="material-icons prefix">mode_edit</i>
      <%= f.label :detail %>
      <%= f.text_area :detail, class: 'materialize-textarea', length: 35 %>
    </div>
  </div>


  <div class="row">
    <div class="center">
      <button class="btn waves-effect waves-light" type="submit" name="action"><%=t 'Post' %></button>
    </div>
  </div>
<% end %>

app/views/worries/index.html.erb
<p class="blue-grey-text text-darken-4"><%=t 'Past Worries' %></p>

<% if @worries.blank? %>
<div>
  <span class="red-text text-lighten-2"><%=t 'Not found.' %></span>
</div>
<% end %>

<% if @worries.present? %>
<div class="collection">
  <% @worries.each do |worry| %>
  <%= link_to worry.detail, worry, class: 'collection-item' %>
  <% end %>
</div>
<% end %>

app/views/worries/new.html.erb
<p class="flow-text blue-grey-text text-darken-4"><%= @reply.message.detail %></p>

<%= render @worry %>

app/views/worries/show.html.erb
<p class="flow-text blue-grey-text text-darken-4"><%= @worry.detail %></p>

<ul class="collection">
<% @sorted_advices[nil].each do |advice| %>
<%= render 'advice', advice: advice %>
<% end %>
</ul>